### Create Author
POST http://127.0.0.1:8080/authors?name=daba12345#

### List Authors
GET http://127.0.0.1:8080/authors

### Get Author by id
GET http://127.0.0.1:8080/authors/1


### List posts
GET http://127.0.0.1:8080/posts

### Create post
POST http://127.0.0.1:8080/posts?title=News&&body=helloworld&&author_id=5

### Get post
GET http://127.0.0.1:8080/posts/3

### Delete post
POST http://127.0.0.1:8080/posts/delete/7
Jwt-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjk2NDA0MzE0fQ.ofnsF_fc9RnwZAXErhs8H83B67tPvWht6BeRTsfQ9ZqCTt4BP0kOFgo6YNb6EIPhgb4MuuOwiUwrzR77tionGg

### UPLOAD FILE
POST http://127.0.0.1:8080/posts/upload
Jwt-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjk2NDEyODEyfQ.JpdXkFRrJ2S1XtmcniS8wcqnCCSX-Fl4eD5vwbx8sBlOuep--933m-1vo2UjCD6gVEgldpqAwtGExllEehLj6w
content-type: application/json

{
  "files": [
    {
      "name": "file1.txt",
      "data": "Base64EncodedDataOfFile1"
    },
    {
      "name": "file2.png",
      "data": "Base64EncodedDataOfFile2"
    }
  ],
  "post_id": 2
}
### CREATE USER
POST http://127.0.0.1:8080/users/?username=Tadasa&&password=LabaDiena

### LOGIN USER
GET http://127.0.0.1:8080/users/login/?username=Tadasa&&password=LabaDiena