### Create Author
POST http://127.0.0.1:8080/authors?name=daba12345#

### List Authors
GET http://127.0.0.1:8080/authors

### Get Author by id
GET http://127.0.0.1:8080/authors/1


### List posts
GET http://127.0.0.1:8080/posts

### Create post
POST http://127.0.0.1:8080/posts?title=News&&body=helloworld&&author_id=5

### Get post
GET http://127.0.0.1:8080/posts/3

### Delete post
POST http://127.0.0.1:8080/posts/delete/7
Jwt-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjk2NDA0MjI5fQ.qmiChMpqzUKPGoQZVynU1vSsVzr1y6ihgd3YLGBJ1TkuJqi9_GN3rN94kdtBSxIjunzuMGStrcp5Kv7c6srkfg

### CREATE USER
POST http://127.0.0.1:8080/users/?username=Tadasa&&password=LabaDiena

### LOGIN USER
GET http://127.0.0.1:8080/users/login/?username=Tadasa&&password=LabaDiena